---
- name: Install Jenkins on Ubuntu
  hosts: jenkins
  become: true
  tasks:

    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install Java (required for Jenkins)
      apt:
        name: openjdk-17-jdk
        state: present

    - name: Add Jenkins repository key
      ansible.builtin.apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        state: present

    - name: Add Jenkins repository
      ansible.builtin.apt_repository:
        repo: "deb https://pkg.jenkins.io/debian-stable binary/"
        state: present

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present
        update_cache: yes

    - name: Ensure Jenkins is running
      systemd:
        name: jenkins
        state: started
        enabled: true

    - name: Print Jenkins initial admin password
      command: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: admin_pass
      changed_when: false

    - name: Display Jenkins admin password
      debug:
        msg: "Jenkins initial admin password: {{ admin_pass.stdout }}"
